services:
  postgres-notificaciones:
    image: postgres:16-alpine
    container_name: clinica-postgres-notificaciones
    environment:
      POSTGRES_DB: clinica_notificaciones_db
      POSTGRES_USER: clinica_notificaciones_user
      POSTGRES_PASSWORD: "${POSTGRES_NOTIFICACIONES_PASSWORD:-ClinicaPostgresLocal123!}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_notificaciones_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clinica_notificaciones_user -d clinica_notificaciones_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-citas:
    image: mongo:7
    container_name: clinica-mongo-citas
    environment:
      MONGO_INITDB_ROOT_USERNAME: clinica_citas_admin
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_CITAS_PASSWORD:-ClinicaMongoLocal123!}"
      MONGO_INITDB_DATABASE: clinica_citas_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_citas_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand(\"ping\").ok' -u clinica_citas_admin -p \"$${MONGO_INITDB_ROOT_PASSWORD}\" --authenticationDatabase admin | grep 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_notificaciones_data:
  mongo_citas_data:
