apiVersion: v1
kind: Namespace
metadata:
  name: clinica-ms
---
apiVersion: v1
kind: Secret
metadata:
  name: clinica-ms-secrets
  namespace: clinica-ms
type: Opaque
stringData:
  mysql-auth-password: ClinicaMysqlLocal123!
  mysql-auth-root-password: ClinicaMysqlRootLocal123!
  mysql-caja-password: ClinicaCajaMysqlLocal123!
  mysql-caja-root-password: ClinicaCajaRootLocal123!
  postgres-atencion-password: ClinicaAtencionPostgresLocal123!
  postgres-notificaciones-password: ClinicaPostgresLocal123!
  mongo-citas-password: ClinicaMongoLocal123!
  auth-admin-password: ClinicaAdminLocal123!
  jwt-secret: Q2xpbmljYURlbW9TZWNyZXRMb2NhbFBhcmFEZXNhcnJvbGxvMjAyNg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clinica-ms-shared-config
  namespace: clinica-ms
data:
  SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
  EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka/
  CORS_ALLOWED_ORIGINS: http://localhost:4200,http://127.0.0.1:4200
