spring.application.name=clinica-gateway-service
server.address=0.0.0.0
server.port=${PORT:8090}

gateway.auth-service-url=${AUTH_SERVICE_URL:http://localhost:8091}
gateway.notificaciones-service-url=${NOTIFICACIONES_SERVICE_URL:http://localhost:8092}
gateway.citas-service-url=${CITAS_SERVICE_URL:http://localhost:8093}
gateway.backend-url=${BACKEND_URL:http://localhost:8080}
gateway.citas-route-enabled=${CITAS_ROUTE_ENABLED:false}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://127.0.0.1:4200}

management.endpoints.web.exposure.include=health
