spring.application.name=clinica-eureka-server
server.address=0.0.0.0
server.port=${PORT:8761}

spring.config.import=${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}

management.endpoints.web.exposure.include=health,info
